#!/bin/bash
# Quick setup de Infinity Mailer en Supabase

echo "📧 Infinity Mailer - Setup Rápido"
echo "=================================="
echo ""
echo "Este script te ayuda a ejecutar el schema SQL en Supabase."
echo ""
echo "PASOS:"
echo "1. Abre https://supabase.com/dashboard"
echo "2. Selecciona proyecto: lirzzskabepwdlhvdmla"
echo "3. Ve a SQL Editor → New query"
echo "4. Copia-pega el contenido de MAILER_SETUP.sql"
echo "5. Presiona RUN"
echo ""
echo "El archivo está en: /home/claudio/mission-control/MAILER_SETUP.sql"
echo ""
read -p "¿Presionar enter cuando termines de ejecutar el schema?"
echo ""
echo "✅ Setup completado!"
echo ""
echo "Próximos pasos:"
echo "1. npm run dev"
echo "2. Abre http://localhost:5173"
echo "3. Ve a http://localhost:5173/mailer"
echo "4. Crea tu primera campaña!"
